export type FontRole = "heading" | "subheading" | "body" | "caption";

export const ALL_ROLES: FontRole[] = ["heading", "subheading", "body", "caption"];

export type FontSlot = {
  role: FontRole;
  family: string;
};

export type FontPairing = {
  id: string;
  vibe: string;
  slots: FontSlot[];
};

export const MIN_SLOTS = 2;
export const MAX_SLOTS = 4;

// --- Categorized pools for dynamic pairing ---

const HEADING_SERIFS = [
  "Playfair Display", "DM Serif Display", "Fraunces", "Cormorant Garamond",
  "Libre Caslon Display", "EB Garamond", "Bodoni Moda", "Crimson Pro",
  "Lora", "Tenor Sans", "Merriweather", "Spectral", "PT Serif", "Vollkorn",
  "Source Serif 4", "Newsreader", "Marcellus", "Libre Bodoni", "Old Standard TT",
  "Libre Baskerville", "Yeseva One", "Arapey", "Arvo", "BioRhyme", "Cardo",
  "Castoro", "Cinzel", "Domine", "Gilda Display", "Inknut Antiqua", "Josefin Serif",
  "Nanum Myeongjo", "Noto Serif", "Prata", "Quattrocento", "Rozha One",
  "Rufina", "Sorts Mill Goudy", "Taviraj", "Tinos", "Trirong", "Unna", "Vidaloka",
  "Zilla Slab", "Roboto Slab", "Alegreya", "Neuton", "Aleo", "Abhaya Libre",
  "Amiri", "Baskervville", "Cormorant", "Faustina", "Luthier", "Martel", "Mate",
  "Oranienbaum", "Petrona", "Vada", "Volkhov", "Bree Serif", "Rokkitt", "Crete Round",
  "Glegoo", "Josefin Slab", "Copse", "Alice", "Halant", "Linden Hill", "Lusitana",
  "Aboreto", "Adamina", "Afacad Flux", "Akaishi", "Alike", "Almendra", "Andada Pro",
  "Antic Slab", "Averia Serif Libre", "Balthazar", "Belgrano", "Bentham", "Besley",
  "Blaka", "Brawler", "Caladea", "Cambay", "Cantata One", "Capriola", "Carme",
  "Chathura", "Chonburi", "Coda", "Codystar", "Cormorant Infant", "Cormorant SC",
  "Cormorant Unicase", "Coustard", "Della Respira", "Dhurjati", "Diplomata",
  "Donegal One", "Dr Sugiyama", "Duru Sans", "Dynalight", "Eagle Lake", "Eater",
  "Economica", "El Messiri", "Electrolize", "Elsie", "Emblema One", "Enriqueta",
  "Erica One", "Esteban", "Euphoria Script", "Ewert", "Expletus Sans", "Fanwood Text",
  "Fascinate", "Federant", "Federo", "Felipa", "Fenix", "Finger Paint", "Flamenco",
  "Flavors", "Fondamento", "Forum", "Fredericka the Great", "Fresca", "Fruktur",
  "Gabriela", "Gafata", "Galada", "Galdeano", "Galindo", "Gentium Book Plus",
  "Geo", "Geostar", "Germania One", "Gidugu", "Gilda Display", "Give You Glory",
  "Glass Antiqua", "Glegoo", "Gloria Hallelujah", "Goblin One", "Gochi Hand",
  "Goudy Bookletter 1911", "Gourmet Script", "Grabber", "Graduate", "Grand Hotel",
  "Gravitas One", "Great Vibes", "Griffy", "Gruppo", "Gudea", "Gurajada", "Habibi",
  "Hachi Maru Pop", "Hammersmith One", "Hanalei", "Hanalei Fill", "Handlee",
  "Hanuman", "Happy Monkey", "Harmattan", "Headland One", "Heebo", "Henny Penny",
  "Hepta Slab", "Herr Von Muellerhoff", "Hi Melody", "Hina Mincho", "Hind",
  "Hind Guntur", "Hind Madurai", "Hind Siliguri", "Hind Vadodara", "Holtwood One SC",
  "Homemade Apple", "Homenaje", "Hubballi", "Huchi", "Ibarra Real Nova",
  "Iceberg", "Iceland", "Imprima", "Indie Flower", "Inter", "Inter Tight",
  "Inika", "Inknut Antiqua", "Irish Grover", "Island Moments", "Istok Web",
  "Italiana", "Italianno", "Itim", "Jacques Francois", "Jacques Francois Shadow",
  "Jaldi", "Jim Nightshade", "Jockey One", "Jolly Lodger", "Jomhuria", "Jots",
  "Josefin Sans", "Josefin Serif", "Joti One", "Jua", "Judson", "Julee", "Julius Sans One",
  "Junge", "Jura", "Just Another Hand", "Just Me Again Down Here", "Kadwa",
  "Kaisei Decol", "Kaisei Opti", "Kaisei Tokumin", "Kalam", "Kameron", "Kanit",
  "Kantumruy Pro", "Karr", "Kaufmann", "Kaushan Script", "Kavivanar", "Kavoon",
  "Kdam Thmor Pro", "Keania One", "Kelly Slab", "Kenia", "Khand", "Khmer",
  "Khula", "Kings", "Kirang Haerang", "Kite One", "Kiwi Maru", "Klee One",
  "Knewave", "KoHo", "Kodchasan", "Koh Santepheap", "Kolker Brush", "Konkhmer Sleokchher",
  "Kosugi", "Kosugi Maru", "Kotta One", "Koulen", "Kranky", "Kray", "Kreon",
  "Kristi", "Krona One", "Krouch", "Kru", "Kufam", "Kulim Park", "Kumar One",
  "Kumar One Outline", "Kumbh Sans", "Kurale", "La Belle Aurore", "Lacquer",
  "Laila", "Lakki Reddy", "Lalezar", "Lancelot", "Lante", "Lara", "Lateef",
  "Lato", "Lavishly Yours", "League Script", "League Spartan", "Leckerli One",
  "Ledger", "Lekton", "Lemon", "Lemonada", "Lexend", "Lexend Deca", "Lexend Exa",
  "Lexend Giga", "Lexend Peta", "Lexend Tera", "Lexend Zetta", "Libre Barcode 128",
  "Libre Barcode 128 Text", "Libre Barcode 39", "Libre Barcode 39 Extended",
  "Libre Barcode 39 Extended Text", "Libre Barcode 39 Text", "Libre Baskerville",
  "Libre Bodoni", "Libre Caslon Display", "Libre Caslon Text", "Libre Franklin",
  "Licorice", "Life Savers", "Lightly", "Lilita One", "Lily Script One", "Limelight",
  "Linden Hill", "Literata", "Liu Jian Mao Cao", "Livvic", "Lobster", "Lobster Two",
  "Londrina Outline", "Londrina Shadow", "Londrina Sketch", "Londrina Solid",
  "Long Cang", "Lora", "Love Ya Like A Sister", "Loved by the King", "Lovers Quarrel",
  "Luckiest Guy", "Lugrasimo", "Lumanosimo", "Luminari", "Lundy", "Lusitana",
  "Lustria", "Luxurious Roman", "Luxurious Script", "M PLUS 1", "M PLUS 1 Code",
  "M PLUS 1p", "M PLUS 2", "M PLUS Rounded 1c", "Ma Shan Zheng", "Macondo",
  "Macondo Swash Caps", "Mada", "Madora", "Magra", "Maiden Orange", "Maitree",
  "Major Mono Display", "Mako", "Mali", "Mallanna", "Mandali", "Manjari", "Manrope",
  "Mansalva", "Mantra", "Marcellus", "Marcellus SC", "Marck Script", "Margarine",
  "Marhey", "Markazi Text", "Marko One", "Marmelad", "Martel", "Martel Sans",
  "Martian Mono", "Marvel", "Mate", "Mate SC", "Maven Pro", "McLaren", "Mea Culpa",
  "Meddon", "MedievalSharp", "Medula One", "Meera Inimai", "Megrim", "Meie Script",
  "Meow Script", "Merienda", "Merienda One", "Merriweather", "Merriweather Sans",
  "Metal", "Metal Mania", "Metamorphous", "Metrophobic", "Michroma", "Milonga",
  "Miltonian", "Miltonian Tattoo", "Mina", "Miniver", "Mingzat", "Miss Fajardose",
  "Mithakas", "Mochi", "Modak", "Modern Antiqua", "Mogra", "Molengo", "Molle",
  "Mondina", "Monofett", "Monoton", "Monsieur La Doulaise", "Montaga", "Montez",
  "Montserrat", "Montserrat Alternates", "Montserrat Subrayada", "Moo Lah Lah",
  "Mookai", "Moon Dance", "Moul", "Moulpali", "Mountains of Christmas", "Mouse Memoirs",
  "Mr Bedfort", "Mr Dafoe", "Mr De Haviland", "Mr Gippi", "Mr Saint Delafield",
  "Mrs Saint Delafield", "Mrs Sheppards", "Ms Madi", "Mukta", "Mukta Mahee",
  "Mukta Malar", "Mukta Vaani", "Mulish", "Murecho", "MuseoModerno", "My Soul",
  "Mynerve", "Mystery Quest", "NTR", "Nabla", "Nadira", "Namdhinggo", "Nanum Brush Script",
  "Nanum Gothic", "Nanum Gothic Coding", "Nanum Myeongjo", "Nanum Pen Script",
  "Narang", "Nars", "Nativa", "Natural", "Naza", "Nehuen", "Neon", "Nepari",
  "Nerko One", "Neucha", "Neuton", "New Rocker", "News Cycle", "Newsreader",
  "Niconne", "Nila", "Niramit", "Nixie One", "Nobile", "Nokora", "Norican",
  "Nosifer", "Notable", "Nothing You Could Do", "Noticia Text", "Noto Color Emoji",
  "Noto Emoji", "Noto Kufi Arabic", "Noto Music", "Noto Naskh Arabic", "Noto Nastaliq Urdu",
  "Noto Rashi Hebrew", "Noto Sans", "Noto Sans Adlam", "Noto Sans Adlam Unjoined",
  "Noto Sans Anatolian Hieroglyphs", "Noto Sans Arabic", "Noto Sans Armenian",
  "Noto Sans Avestan", "Noto Sans Balinese", "Noto Sans Bamum", "Noto Sans Bassa Vah",
  "Noto Sans Batak", "Noto Sans Bengali", "Noto Sans Bhaiksuki", "Noto Sans Brahmi",
  "Noto Sans Buginese", "Noto Sans Buhid", "Noto Sans Canadian Aboriginal",
  "Noto Sans Carian", "Noto Sans Caucasian Albanian", "Noto Sans Chakma",
  "Noto Sans Cham", "Noto Sans Cherokee", "Noto Sans Coptic", "Noto Sans Cuneiform",
  "Noto Sans Cypriot", "Noto Sans Deseret", "Noto Sans Devanagari", "Noto Sans Duployan",
  "Noto Sans Egyptian Hieroglyphs", "Noto Sans Elbasan", "Noto Sans Ethiopic",
  "Noto Sans Georgian", "Noto Sans Glagolitic", "Noto Sans Gothic", "Noto Sans Grantha",
  "Noto Sans Gujarati", "Noto Sans Gunjala Gondi", "Noto Sans Gurmukhi",
  "Noto Sans Hanifi Rohingya", "Noto Sans Hanunoo", "Noto Sans Hatran",
  "Noto Sans Hebrew", "Noto Sans Imperial Aramaic", "Noto Sans Indic Siyaq Numbers",
  "Noto Sans Inscriptional Pahlavi", "Noto Sans Inscriptional Parthian",
  "Noto Sans Javanese", "Noto Sans Kaithi", "Noto Sans Kannada", "Noto Sans Kayah Li",
  "Noto Sans Kharoshthi", "Noto Sans Khmer", "Noto Sans Khojki", "Noto Sans Khudawadi",
  "Noto Sans Lao", "Noto Sans Lao Looped", "Noto Sans Lepcha", "Noto Sans Limbu",
  "Noto Sans Linear A", "Noto Sans Linear B", "Noto Sans Lisu", "Noto Sans Lycian",
  "Noto Sans Lydian", "Noto Sans Mahajani", "Noto Sans Malayalam", "Noto Sans Mandaic",
  "Noto Sans Manichaean", "Noto Sans Marchen", "Noto Sans Masaram Gondi",
  "Noto Sans Math", "Noto Sans Mayan Numerals", "Noto Sans Medefaidrin",
  "Noto Sans Meetei Mayek", "Noto Sans Mende Kikakui", "Noto Sans Meroitic",
  "Noto Sans Miao", "Noto Sans Modi", "Noto Sans Mongolian", "Noto Sans Mono",
  "Noto Sans Mro", "Noto Sans Multani", "Noto Sans Myanmar", "Noto Sans NKo",
  "Noto Sans Nabataean", "Noto Sans Nag Mundari", "Noto Sans Nandinagari",
  "Noto Sans New Tai Lue", "Noto Sans Newa", "Noto Sans Nushu", "Noto Sans Ogham",
  "Noto Sans Ol Chiki", "Noto Sans Old Hungarian", "Noto Sans Old Italic",
  "Noto Sans Old North Arabian", "Noto Sans Old Permic", "Noto Sans Old Persian",
  "Noto Sans Old Sogdian", "Noto Sans Old South Arabian", "Noto Sans Old Turkic",
  "Noto Sans Oriya", "Noto Sans Osage", "Noto Sans Osmanya", "Noto Sans Pahawh Hmong",
  "Noto Sans Palmyrene", "Noto Sans Pau Cin Hau", "Noto Sans Phags Pa",
  "Noto Sans Phoenician", "Noto Sans Psalter Pahlavi", "Noto Sans Rejang",
  "Noto Sans Runic", "Noto Sans Samaritan", "Noto Sans Saurashtra", "Noto Sans Sharada",
  "Noto Sans Shavian", "Noto Sans Siddham", "Noto Sans Sinhala", "Noto Sans Sogdian",
  "Noto Sans Sora Sompeng", "Noto Sans Soyombo", "Noto Sans Sundanese",
  "Noto Sans Syloti Nagri", "Noto Sans Symbols", "Noto Sans Symbols 2",
  "Noto Sans Syriac", "Noto Sans Tagalog", "Noto Sans Tagbanwa", "Noto Sans Tai Le",
  "Noto Sans Tai Tham", "Noto Sans Tai Viet", "Noto Sans Takri", "Noto Sans Tamil",
  "Noto Sans Tamil Supplement", "Noto Sans Tangsa", "Noto Sans Telugu",
  "Noto Sans Thaana", "Noto Sans Thai", "Noto Sans Thai Looped", "Noto Sans Tifinagh",
  "Noto Sans Tirhuta", "Noto Sans Ugaritic", "Noto Sans Vai", "Noto Sans Wancho",
  "Noto Sans Warang Citi", "Noto Sans Yi", "Noto Sans Zanabazar Square",
  "Noto Serif", "Noto Serif Armenian", "Noto Serif Bengali", "Noto Serif Devanagari",
  "Noto Serif Dogra", "Noto Serif Ethiopic", "Noto Serif Georgian", "Noto Serif Gujarati",
  "Noto Serif Gurmukhi", "Noto Serif Hebrew", "Noto Serif Kannada", "Noto Serif Khmer",
  "Noto Serif Khojki", "Noto Serif Lao", "Noto Serif Malayalam", "Noto Serif Myanmar",
  "Noto Serif Oriya", "Noto Serif Sinhala", "Noto Serif Tamil", "Noto Serif Tangut",
  "Noto Serif Telugu", "Noto Serif Thai", "Noto Serif Tibetan", "Noto Serif Yezidi",
  "Noto Traditional Nushu", "Nova Cut", "Nova Flat", "Nova Mono", "Nova Oval",
  "Nova Round", "Nova Script", "Nova Slim", "Nova Square", "Numans", "Nunito",
  "Nunito Sans", "Nuosu", "Odor Mean Chey", "Offside", "Oi", "Old Standard TT",
  "Oldenburg", "Ole", "Oleo Script", "Oleo Script Swash Caps", "Onest", "Open Sans",
  "Oranienbaum", "Orbitron", "Oregano", "Oregano", "Orienta", "Original Surfer",
  "Oswald", "Outfit", "Over the Rainbow", "Overlock", "Overlock SC", "Overpass",
  "Overpass Mono", "Ovo", "Oxanium", "Oxygen", "Oxygen Mono", "PT Mono", "PT Sans",
  "PT Sans Caption", "PT Sans Narrow", "PT Serif", "PT Serif Caption", "Pacifico",
  "Padauk", "Padyakke Expanded One", "Palanquin", "Palanquin Dark", "Pangolin",
  "Paprika", "Parisienne", "Passero One", "Passion One", "Passions Conflict",
  "Pathway Extreme", "Pathway Gothic One", "Patrick Hand", "Patrick Hand SC",
  "Pattaya", "Patua One", "Pavanam", "Paytone One", "Peddana", "Peralta", "Petit Formal Script",
  "Petrona", "Philosopher", "Phudu", "Piazzolla", "Pie", "Piedra", "Pinyon Script",
  "Pirata One", "Plaster", "Play", "Playball", "Playfair", "Playfair Display",
  "Playfair Display SC", "Plus Jakarta Sans", "Podkova", "Poiret One", "Poller One",
  "Poly", "Pompiere", "Pontano Sans", "Poor Story", "Poppins", "Port Lligat Caption",
  "Port Lligat Slab", "Potta One", "Prata", "Preahvihear", "Press Start 2P",
  "Pridi", "Princess Sofia", "Prociono", "Prompt", "Prosto One", "Proza Libre",
  "Public Sans", "Puppert", "Puritan", "Purple Purse", "Qahiri", "Quanto", "Quattrocento",
  "Quattrocento Sans", "Questrial", "Quicksand", "Quintessential", "Qwigley",
  "Qwitcher Grypen", "Racing Sans One", "Radley", "Rajdhani", "Rakkas", "Raleway",
  "Raleway Dots", "Ramabhadra", "Ramaraja", "Rambla", "Rammetto One", "Rampart One",
  "Ranchers", "Rancho", "Ranga", "Rasa", "Rationale", "Ravi Prakash", "Readex Pro",
  "Recursive", "Red Hat Display", "Red Hat Mono", "Red Hat Text", "Redrose",
  "Reenie Beanie", "Reggae One", "Revalia", "Rhodium Libre", "Ribeye", "Ribeye Marrow",
  "Righteous", "Risque", "Road Rage", "Roboto", "Roboto Condensed", "Roboto Flex",
  "Roboto Mono", "Roboto Serif", "Roboto Slab", "Rochester", "Rock Salt",
  "Rokkitt", "Romanesco", "Ropa Sans", "Rosario", "Rosarivo", "Rouge Script",
  "Rowdies", "Rozha One", "Rubik", "Rubik 80s Fade", "Rubik Beastly", "Rubik Bubbles",
  "Rubik Burned", "Rubik Distressed", "Rubik Glitch", "Rubik Iso", "Rubik Lines",
  "Rubik Marker Hatch", "Rubik Maze", "Rubik Microbe", "Rubik Moonrocks",
  "Rubik Puddles", "Rubik Wet Paint", "Ruda", "Rufina", "Ruge Boogie", "Ruluko",
  "Rum Raisin", "Ruslan Display", "Russo One", "Ruthie", "Rye", "STIX Two Text",
  "Sacramento", "Sahitya", "Sail", "Saira", "Saira Condensed", "Saira Extra Condensed",
  "Saira Semi Condensed", "Saira Stencil One", "Salsa", "Sanchez", "Sancreek",
  "Sansita", "Sansita Swashed", "Sarabun", "Sarala", "Sarina", "Sarpanch",
  "Sassy Frass", "Satisfy", "Saurashtra", "Sawarabi Gothic", "Sawarabi Mincho",
  "Scada", "Scheherazade New", "Schoolbell", "Scope One", "Seaweed Script",
  "Secular One", "Sedgwick Ave", "Sedgwick Ave Display", "Sen", "Sevillana",
  "Seymour One", "Shadows Into Light", "Shadows Into Light Two", "Shalimar",
  "Shanti", "Share", "Share Tech", "Share Tech Mono", "Shippori Mincho",
  "Shippori Mincho B1", "Shrikhand", "Siemreap", "Sigmar", "Sigmar One", "Signika",
  "Signika Negative", "Silkscreen", "Simonetta", "Single Day", "Sintony",
  "Sirin Stencil", "Six Caps", "Skranji", "Slabo 13px", "Slabo 27px", "Slackey",
  "Smokum", "Smooch", "Smooch Sans", "Smythe", "Sniglet", "Snippet", "Snowburst One",
  "Sofadi One", "Sofia", "Sofia Sans", "Sofia Sans Condensed", "Sofia Sans Extra Condensed",
  "Sofia Sans Semi Condensed", "Solitreo", "Solway", "Song Myung", "Sono", "Sora",
  "Sorts Mill Goudy", "Source Code Pro", "Source Sans 3", "Source Sans Pro",
  "Source Serif 4", "Source Serif Pro", "Space Grotesk", "Space Mono", "Special Elite",
  "Spectral", "Spectral SC", "Spicy Rice", "Spinnaker", "Spirax", "Spline Sans",
  "Spline Sans Mono", "Squada One", "Sree Krushnadevaraya", "Sriracha", "Stalemate",
  "Stalinist One", "Stardos Stencil", "Stataco", "Step", "Stint Ultra Condensed",
  "Stint Ultra Expanded", "Stoke", "Strait", "Style Script", "Stylish", "Sue Ellen Francisco",
  "Suez One", "Sulphur Point", "Sumana", "Sunshiney", "Supermercado One",
  "Sura", "Suranna", "Suravaram", "Suwannaphum", "Swanky and Moo Moo", "Syncopate",
  "Syne", "Syne Mono", "Tactile", "Tagu", "Tai Heritage Pro", "Tajawal", "Tangerine",
  "Tant", "Taprom", "Tauri", "Taviraj", "Teko", "Telex", "Tenali Ramakrishna",
  "Tenor Sans", "Text Me One", "Texturina", "Thabit", "Thasadith", "The Girl Next Door",
  "Tienne", "Tila", "Tillana", "Tilt Neon", "Tilt Prism", "Tilt Warp", "Timmana",
  "Tinos", "Tiro Bangla", "Tiro Devanagari Hindi", "Tiro Devanagari Marathi",
  "Tiro Devanagari Sanskrit", "Tiro Gurmukhi", "Tiro Kannada", "Tiro Tamil",
  "Tiro Telugu", "Titan One", "Titillium Web", "Tomorrow", "Tourney", "Townsend",
  "Trade Winds", "Train One", "Trirong", "Trispace", "Trocchi", "Trochut",
  "Truculenta", "Trykker", "Tulpen One", "Turret Road", "Ubuntu", "Ubuntu Condensed",
  "Ubuntu Mono", "Uchen", "Ultra", "Unbounded", "Uncial Antiqua", "Underdog",
  "Unica One", "UnifrakturCook", "UnifrakturMaguntia", "Unkempt", "Unlock",
  "Unna", "Updock", "Urbanist", "VT323", "Vampiro One", "Varela", "Varela Round",
  "Vasa", "Vast Shadow", "Vesper Libre", "Viaoda Libre", "Vibur", "Vidaloka",
  "Viga", "Villa", "Vina Sans", "Vincas", "Ving", "Vollkorn", "Vollkorn SC",
  "Volkhov", "Voltaire", "Vremne", "Waiting for the Sunrise", "Wallpoet",
  "Walter Turncoat", "Warnes", "Water Brush", "Waterfall", "Wave", "Wellfleet",
  "Wendy One", "Whisper", "WindSong", "Wire One", "Work Sans", "Xanh Mono",
  "Yaldevi", "Yanone Kaffeesatz", "Yantramanav", "Yatra One", "Yellowtail",
  "Yeon Sung", "Yeseva One", "Yesteryear", "Yive", "Yizhi", "Yomogi", "Young Serif",
  "Yusei Magic", "Zantant", "Zcool KuaiLe", "Zcool QingKe HuangYou", "Zcool XiaoWei",
  "Zen Dots", "Zen Kaku Gothic Antique", "Zen Kaku Gothic New", "Zen Maru Gothic",
  "Zen Old Mincho", "Zen Tokyo Zoo", "Zeyada", "Zhi Mang Xing", "Zilla Slab",
  "Zilla Slab Highlight"
];

const HEADING_DISPLAY_SANS = [
  "Syne", "Bricolage Grotesque", "Space Grotesk", "Archivo", "Rubik", "Raleway",
  "Montserrat", "Bebas Neue", "Anton", "Antonio", "Familjen Grotesk", "Chivo",
  "Hanken Grotesk", "Sora", "Unbounded", "Big Shoulders Display", "Archivo Black",
  "Cabinet Grotesque", "Calistoga", "Capriola", "Clash Display", "Darker Grotesque",
  "Fugaz One", "Goldman", "Kanit", "Kumbh Sans", "Lexend Deca", "Museomoderno",
  "Orbitron", "Oswald", "Outfit", "Passion One", "Paytone One", "Philosopher",
  "Righteous", "Russo One", "Secular One", "Titan One", "Tomorrow", "Urbanist",
  "Knewave", "Krona One", "Bungee", "Carter One", "Chewy", "Changa One", "Francois One",
  "Fredoka", "Shrikhand", "Sigmar One", "Viga", "Alfa Slab One", "Bowlby One",
  "Concert One", "Corben", "Eczar", "Fascinate", "Graduate", "Limelight", "Londrina Solid",
  "Luckiest Guy", "Monoton", "Nixie One", "Oleo Script", "Patua One", "Poller One",
  "Rammetto One", "Rowdies", "Shojumaru", "Sriracha", "Stardos Stencil", "Ultra",
  "Unica One", "Vast Shadow", "Fjalla One", "Racing Sans One",
  "Abel", "Abril Fatface", "Aclonica", "Acme", "Akaya Kanadaka", "Akaya Telivigala",
  "Aladin", "Alatsi", "Aldrich", "Alef", "Alegreya Sans SC", "Alex Brush",
  "Alfa Slab One", "Alice", "Alike", "Alike Angular", "Allan", "Allerta",
  "Allerta Stencil", "Allura", "Almarai", "Almendra", "Almendra Display",
  "Almendra SC", "Amarante", "Amaranth", "Amatic SC", "Amethysta", "Amiko",
  "Amiri", "Amita", "Anaheim", "Andada Pro", "Andika", "Anek Bangla", "Anek Devanagari",
  "Anek Gujarati", "Anek Gurmukhi", "Anek Kannada", "Anek Malayalam", "Anek Odia",
  "Anek Tamil", "Anek Telugu", "Angkor", "Annie Use Your Telescope", "Anonymous Pro",
  "Antic", "Antic Didone", "Antic Slab", "Anton", "Antonio", "Anywhere", "Arapey",
  "Arbutus", "Arbutus Slab", "Architects Daughter", "Archivo", "Archivo Black",
  "Archivo Narrow", "Are You Serious", "Aref Ruqaa", "Arima", "Arima Madurai",
  "Arimo", "Arizonia", "Armata", "Arsenal", "Artifika", "Arvo", "Arya", "Asap",
  "Asap Condensed", "Asar", "Asset", "Assistant", "Astloch", "Asul", "Athiti",
  "Atma", "Atomic Age", "Aubray", "Audiowide", "Autour One", "Average",
  "Average Sans", "Averia Gruesa Libre", "Averia Libre", "Averia Sans Libre",
  "Averia Serif Libre", "Azeret Mono", "B612", "B612 Mono", "Bad Script",
  "Bahiana", "Bahianita", "Bai Jamjuree", "Bakbak One", "Baloo 2", "Baloo Bhai 2",
  "Baloo Bhaijaan 2", "Baloo Bhaina 2", "Baloo Chettan 2", "Baloo Da 2",
  "Baloo Paaji 2", "Baloo Tamma 2", "Baloo Tammudu 2", "Baloo Thambi 2", "Balsamiq Sans",
  "Balthazar", "Bangers", "Barlow", "Barlow Condensed", "Barlow Semi Condensed",
  "Barriecito", "Barrio", "Basic", "Baskervville", "Battambang", "Baumans",
  "Bayon", "Be Vietnam Pro", "Bebas Neue", "Belgrano", "Bellefair", "Belleza",
  "Bellota", "Bellota Text", "BenchNine", "Benne", "Bentham", "Berkshire Swash",
  "Besley", "Beth Ellen", "Bevan", "BhuTuka Expanded One", "Big Shoulders Display",
  "Big Shoulders Inline Display", "Big Shoulders Inline Text", "Big Shoulders Stencil Display",
  "Big Shoulders Stencil Text", "Big Shoulders Text", "Bigelow Rules", "Bigshot One",
  "Bilbo", "Bilbo Swash Caps", "BioRhyme", "BioRhyme Expanded", "Birthstone",
  "Birthstone Bounce", "Biryani", "Bitter", "Black And White Picture", "Black Han Sans",
  "Black Ops One", "Blaka", "Blaka Hollow", "Blinker", "Bodoni Moda", "Bohème",
  "Bokor", "Bona Nova", "Bonbon", "Bonheur Royale", "Boogaloo", "Bowlby One",
  "Bowlby One SC", "Brawler", "Bree Serif", "Brygada 1918", "Bubblegum Sans",
  "Bubbler One", "Buda", "Buenard", "Bungee", "Bungee Hairline", "Bungee Inline",
  "Bungee Outline", "Bungee Shade", "Bungee Spice", "Butcherman", "Butterfly Kids",
  "Cabin", "Cabin Condensed", "Cabin Sketch", "Caesar Dressing", "Cagliostro",
  "Cairo", "Cairo Play", "Caladea", "Calistoga", "Calligraffitti", "Cambay",
  "Cambo", "Candal", "Cantarell", "Cantata One", "Cantora One", "Capriola",
  "Caramel", "Carattere", "Cardo", "Carme", "Carrois Gothic", "Carrois Gothic SC",
  "Carter One", "Castoro", "Castoro Titling", "Catamaran", "Caudex", "Caveat",
  "Caveat Brush", "Cedarville Cursive", "Ceviche One", "Chakra Petch", "Changa",
  "Changa One", "Chanthaburi", "Chanti", "Charis SIL", "Charm", "Charmonman",
  "Chathura", "Chau Philomene One", "Chela One", "Chelsea Market", "Chenla",
  "Cherish", "Cherry Cream Soda", "Cherry Swash", "Chewy", "Chicle", "Chilanka",
  "Chivo", "Chivo Mono", "Chonburi", "Cinzel", "Cinzel Decorative", "Clicker Script",
  "Coda", "Coda Caption", "Codystar", "Coiny", "Combo", "Comfortaa", "Comforter",
  "Comforter Brush", "Comic Neue", "Coming Soon", "Commissioner", "Concert One",
  "Condiment", "Content", "Contrail One", "Convergence", "Cookie", "Copse",
  "Corben", "Corinthia", "Cormorant", "Cormorant Garamond", "Cormorant Infant",
  "Cormorant SC", "Cormorant Unicase", "Cormorant Upright", "Courgette",
  "Courier Prime", "Cousine", "Coustard", "Covered By Your Grace", "Crafty Girls",
  "Creepster", "Crete Round", "Crimson Pro", "Crimson Text", "Croissant One",
  "Crushed", "Cuprum", "Cute Font", "Cutive", "Cutive Mono", "DM Mono", "DM Sans",
  "DM Serif Display", "DM Serif Text", "Damion", "Dancing Script", "Dangrek",
  "Darker Grotesque", "Darumadrop One", "David Libre", "Dawning of a New Day",
  "Days One", "Dekko", "Delius", "Delius Swash Caps", "Delius Unicase", "Della Respira",
  "Denk One", "Devonshire", "Dhurjati", "Didact Gothic", "Diplomata", "Diplomata SC",
  "Do Hyeon", "Dokdo", "Domine", "Donegal One", "Doppio One", "Dorsa", "Dosis",
  "DotGothic16", "Dr Sugiyama", "Duru Sans", "Dynalight", "EB Garamond", "Eagle Lake",
  "East Sea Dokdo", "Eater", "Economica", "Eczar", "Edu NSW ACT Foundation",
  "Edu QLD Beginner", "Edu SA Beginner", "Edu TAS Beginner", "Edu VIC WA NT Beginner",
  "El Messiri", "Electrolize", "Elsie", "Elsie Swash Caps", "Emblema One",
  "Emilys Candy", "Encode Sans", "Encode Sans Condensed", "Encode Sans Expanded",
  "Encode Sans Semi Condensed", "Encode Sans Semi Expanded", "Engagement",
  "Englebert", "Enriqueta", "Ephesis", "Epilogue", "Erica One", "Esteban",
  "Estonia", "Euphoria Script", "Ewert", "Exo", "Exo 2", "Expletus Sans",
  "Explora", "Fahkwang", "Familjen Grotesk", "Fanwood Text", "Farro", "Fascinate",
  "Fascinate Inline", "Faster One", "Fasthand", "Fauna One", "Faustina", "Federant",
  "Federo", "Felipa", "Fenix", "Festive", "Figtree", "Finger Paint", "Fira Code",
  "Fira Mono", "Fira Sans", "Fira Sans Condensed", "Fira Sans Extra Condensed",
  "Fjalla One", "Fjord One", "Flamenco", "Flavors", "Fleur De Leah", "Flow Block",
  "Flow Circular", "Flow Rounded", "Fondamento", "Fontdiner Swanky", "Forum",
  "Fragment Mono", "Francois One", "Frank Ruhl Libre", "Fraunces", "Fredericka the Great",
  "Fredoka", "Freehand", "Fresca", "Fruktur", "Fugaz One", "Fuggles", "Fuzzy Bubbles",
  "GFS Didot", "GFS Neohellenic", "Gabriela", "Gaegu", "Gafata", "Gajraj One",
  "Galada", "Galdeano", "Galindo", "Gamja Flower", "Gantari", "Gasa One", "Gayathri",
  "Gelasio", "Gemunu Libre", "Genos", "Gentium Book Plus", "Gentium Plus", "Geo",
  "Georama", "Geostar", "Geostar Fill", "Germania One", "Gideon Roman", "Gidugu",
  "Gilda Display", "Girassol", "Give You Glory", "Glass Antiqua", "Glegoo",
  "Gloria Hallelujah", "Glory", "Gluten", "Goblin One", "Gochi Hand", "Goldman",
  "Golos Text", "Gomapu", "Gorditas", "Gothic A1", "Goudy Bookletter 1911",
  "Gowun Batang", "Gowun Dodum", "Graduate", "Grand Hotel", "Grandstander",
  "Grape Nuts", "Gravitas One", "Great Vibes", "Grechen Fuemen", "Grenze",
  "Grenze Gotisch", "Grey Qo", "Griffy", "Gruppo", "Gudea", "Gugi", "Gulzar",
  "Gurajada", "Gwendolyn", "Habibi", "Hachi Maru Pop", "Hahmlet", "Halant",
  "Hammersmith One", "Hanalei", "Hanalei Fill", "Handlee", "Hanken Grotesk",
  "Hanuman", "Happy Monkey", "Harmattan", "Headland One", "Heebo", "Henny Penny",
  "Hepta Slab", "Herr Von Muellerhoff", "Hi Melody", "Hina Mincho", "Hind",
  "Hind Guntur", "Hind Madurai", "Hind Siliguri", "Hind Vadodara", "Holtwood One SC",
  "Homemade Apple", "Homenaje", "Hubballi", "Huchi", "Hurricane", "IBM Plex Mono",
  "IBM Plex Sans", "IBM Plex Sans Arabic", "IBM Plex Sans Condensed",
  "IBM Plex Sans Devanagari", "IBM Plex Sans Hebrew", "IBM Plex Sans JP",
  "IBM Plex Sans KR", "IBM Plex Sans Thai", "IBM Plex Sans Thai Looped",
  "IBM Plex Serif", "IM Fell DW Pica", "IM Fell DW Pica SC", "IM Fell Double Pica",
  "IM Fell Double Pica SC", "IM Fell English", "IM Fell English SC",
  "IM Fell French Canon", "IM Fell French Canon SC", "IM Fell Great Primer",
  "IM Fell Great Primer SC", "Ibarra Real Nova", "Iceberg", "Iceland", "Imprima",
  "Inconsolata", "Indie Flower", "Ingrid Darling", "Inika", "Inknut Antiqua",
  "Inria Sans", "Inria Serif", "Inspiration", "Instrument Sans", "Instrument Serif",
  "Inter", "Inter Tight", "Island Moments", "Istok Web", "Italiana", "Italianno",
  "Itim", "Jacques Francois", "Jacques Francois Shadow", "Jaldi", "JetBrains Mono",
  "Jim Nightshade", "Jockey One", "Jolly Lodger", "Jomhuria", "Josefin Sans",
  "Josefin Serif", "Jost", "Joti One", "Jua", "Judson", "Julee", "Julius Sans One",
  "Junge", "Jura", "Just Another Hand", "Just Me Again Down Here", "KOTTA One",
  "Kadwa", "Kaisei Decol", "Kaisei Opti", "Kaisei Tokumin", "Kalam", "Kameron",
  "Kanit", "Kantumruy Pro", "Karla", "Karma", "Katibeh", "Kaufmann", "Kaushan Script",
  "Kavivanar", "Kavoon", "Kdam Thmor Pro", "Keania One", "Kelly Slab", "Kenia",
  "Khand", "Khmer", "Khula", "Kings", "Kirang Haerang", "Kite One", "Kiwi Maru",
  "Klee One", "Knewave", "KoHo", "Kodchasan", "Koh Santepheap", "Kolker Brush",
  "Konkhmer Sleokchher", "Kosugi", "Kosugi Maru", "Kotta One", "Koulen", "Kranky",
  "Kray", "Kreon", "Kristi", "Krona One", "Krouch", "Kru", "Kufam", "Kulim Park",
  "Kumar One", "Kumar One Outline", "Kumbh Sans", "Kurale", "La Belle Aurore",
  "Lacquer", "Laila", "Lakki Reddy", "Lalezar", "Lancelot", "Lante", "Lateef",
  "Lato", "Lavishly Yours", "League Script", "League Spartan", "Leckerli One",
  "Ledger", "Lekton", "Lemon", "Lemonada", "Lexend", "Lexend Deca", "Lexend Exa",
  "Lexend Giga", "Lexend Peta", "Lexend Tera", "Lexend Zetta", "Libre Barcode 128",
  "Libre Barcode 128 Text", "Libre Barcode 39", "Libre Barcode 39 Extended",
  "Libre Barcode 39 Extended Text", "Libre Barcode 39 Text", "Libre Baskerville",
  "Libre Bodoni", "Libre Caslon Display", "Libre Caslon Text", "Libre Franklin",
  "Licorice", "Life Savers", "Lightly", "Lilita One", "Lily Script One", "Limelight",
  "Linden Hill", "Literata", "Liu Jian Mao Cao", "Livvic", "Lobster", "Lobster Two",
  "Londrina Outline", "Londrina Shadow", "Londrina Sketch", "Londrina Solid",
  "Long Cang", "Lora", "Love Ya Like A Sister", "Loved by the King", "Lovers Quarrel",
  "Luckiest Guy", "Lugrasimo", "Lumanosimo", "Luminari", "Lundy", "Lusitana",
  "Lustria", "Luxurious Roman", "Luxurious Script", "M PLUS 1", "M PLUS 1 Code",
  "M PLUS 1p", "M PLUS 2", "M PLUS Rounded 1c", "Ma Shan Zheng", "Macondo",
  "Macondo Swash Caps", "Mada", "Madora", "Magra", "Maiden Orange", "Maitree",
  "Major Mono Display", "Mako", "Mali", "Mallanna", "Mandali", "Manjari", "Manrope",
  "Mansalva", "Mantra", "Marcellus", "Marcellus SC", "Marck Script", "Margarine",
  "Marhey", "Markazi Text", "Marko One", "Marmelad", "Martel", "Martel Sans",
  "Martian Mono", "Marvel", "Mate", "Mate SC", "Maven Pro", "McLaren", "Mea Culpa",
  "Meddon", "MedievalSharp", "Medula One", "Meera Inimai", "Megrim", "Meie Script",
  "Meow Script", "Merienda", "Merienda One", "Merriweather", "Merriweather Sans",
  "Metal", "Metal Mania", "Metamorphous", "Metrophobic", "Michroma", "Milonga",
  "Miltonian", "Miltonian Tattoo", "Mina", "Miniver", "Mingzat", "Miss Fajardose",
  "Mithakas", "Mochi", "Modak", "Modern Antiqua", "Mogra", "Molengo", "Molle",
  "Mondina", "Monofett", "Monoton", "Monsieur La Doulaise", "Montaga", "Montez",
  "Montserrat", "Montserrat Alternates", "Montserrat Subrayada", "Moo Lah Lah",
  "Mookai", "Moon Dance", "Moul", "Moulpali", "Mountains of Christmas", "Mouse Memoirs",
  "Mr Bedfort", "Mr Dafoe", "Mr De Haviland", "Mr Gippi", "Mr Saint Delafield",
  "Mrs Saint Delafield", "Mrs Sheppards", "Ms Madi", "Mukta", "Mukta Mahee",
  "Mukta Malar", "Mukta Vaani", "Mulish", "Murecho", "MuseoModerno", "My Soul",
  "Mynerve", "Mystery Quest", "NTR", "Nabla", "Nadira", "Namdhinggo", "Nanum Brush Script",
  "Nanum Gothic", "Nanum Gothic Coding", "Nanum Myeongjo", "Nanum Pen Script",
  "Narang", "Nars", "Nativa", "Natural", "Naza", "Nehuen", "Neon", "Nepari",
  "Nerko One", "Neucha", "Neuton", "New Rocker", "News Cycle", "Newsreader",
  "Niconne", "Nila", "Niramit", "Nixie One", "Nobile", "Nokora", "Norican",
  "Nosifer", "Notable", "Nothing You Could Do", "Noticia Text", "Noto Color Emoji",
  "Noto Emoji", "Noto Kufi Arabic", "Noto Music", "Noto Naskh Arabic", "Noto Nastaliq Urdu",
  "Noto Rashi Hebrew", "Noto Sans", "Noto Sans Adlam", "Noto Sans Adlam Unjoined",
  "Noto Sans Anatolian Hieroglyphs", "Noto Sans Arabic", "Noto Sans Armenian",
  "Noto Sans Avestan", "Noto Sans Balinese", "Noto Sans Bamum", "Noto Sans Bassa Vah",
  "Noto Sans Batak", "Noto Sans Bengali", "Noto Sans Bhaiksuki", "Noto Sans Brahmi",
  "Noto Sans Buginese", "Noto Sans Buhid", "Noto Sans Canadian Aboriginal",
  "Noto Sans Carian", "Noto Sans Caucasian Albanian", "Noto Sans Chakma",
  "Noto Sans Cham", "Noto Sans Cherokee", "Noto Sans Coptic", "Noto Sans Cuneiform",
  "Noto Sans Cypriot", "Noto Sans Deseret", "Noto Sans Devanagari", "Noto Sans Duployan",
  "Noto Sans Egyptian Hieroglyphs", "Noto Sans Elbasan", "Noto Sans Ethiopic",
  "Noto Sans Georgian", "Noto Sans Glagolitic", "Noto Sans Gothic", "Noto Sans Grantha",
  "Noto Sans Gujarati", "Noto Sans Gunjala Gondi", "Noto Sans Gurmukhi",
  "Noto Sans Hanifi Rohingya", "Noto Sans Hanunoo", "Noto Sans Hatran",
  "Noto Sans Hebrew", "Noto Sans Imperial Aramaic", "Noto Sans Indic Siyaq Numbers",
  "Noto Sans Inscriptional Pahlavi", "Noto Sans Inscriptional Parthian",
  "Noto Sans Javanese", "Noto Sans Kaithi", "Noto Sans Kannada", "Noto Sans Kayah Li",
  "Noto Sans Kharoshthi", "Noto Sans Khmer", "Noto Sans Khojki", "Noto Sans Khudawadi",
  "Noto Sans Lao", "Noto Sans Lao Looped", "Noto Sans Lepcha", "Noto Sans Limbu",
  "Noto Sans Linear A", "Noto Sans Linear B", "Noto Sans Lisu", "Noto Sans Lycian",
  "Noto Sans Lydian", "Noto Sans Mahajani", "Noto Sans Malayalam", "Noto Sans Mandaic",
  "Noto Sans Manichaean", "Noto Sans Marchen", "Noto Sans Masaram Gondi",
  "Noto Sans Math", "Noto Sans Mayan Numerals", "Noto Sans Medefaidrin",
  "Noto Sans Meetei Mayek", "Noto Sans Mende Kikakui", "Noto Sans Meroitic",
  "Noto Sans Miao", "Noto Sans Modi", "Noto Sans Mongolian", "Noto Sans Mono",
  "Noto Sans Mro", "Noto Sans Multani", "Noto Sans Myanmar", "Noto Sans NKo",
  "Noto Sans Nabataean", "Noto Sans Nag Mundari", "Noto Sans Nandinagari",
  "Noto Sans New Tai Lue", "Noto Sans Newa", "Noto Sans Nushu", "Noto Sans Ogham",
  "Noto Sans Ol Chiki", "Noto Sans Old Hungarian", "Noto Sans Old Italic",
  "Noto Sans Old North Arabian", "Noto Sans Old Permic", "Noto Sans Old Persian",
  "Noto Sans Old Sogdian", "Noto Sans Old South Arabian", "Noto Sans Old Turkic",
  "Noto Sans Oriya", "Noto Sans Osage", "Noto Sans Osmanya", "Noto Sans Pahawh Hmong",
  "Noto Sans Palmyrene", "Noto Sans Pau Cin Hau", "Noto Sans Phags Pa",
  "Noto Sans Phoenician", "Noto Sans Psalter Pahlavi", "Noto Sans Rejang",
  "Noto Sans Runic", "Noto Sans Samaritan", "Noto Sans Saurashtra", "Noto Sans Sharada",
  "Noto Sans Shavian", "Noto Sans Siddham", "Noto Sans Sinhala", "Noto Sans Sogdian",
  "Noto Sans Sora Sompeng", "Noto Sans Soyombo", "Noto Sans Sundanese",
  "Noto Sans Syloti Nagri", "Noto Sans Symbols", "Noto Sans Symbols 2",
  "Noto Sans Syriac", "Noto Sans Tagalog", "Noto Sans Tagbanwa", "Noto Sans Tai Le",
  "Noto Sans Tai Tham", "Noto Sans Tai Viet", "Noto Sans Takri", "Noto Sans Tamil",
  "Noto Sans Tamil Supplement", "Noto Sans Tangsa", "Noto Sans Telugu",
  "Noto Sans Thaana", "Noto Sans Thai", "Noto Sans Thai Looped", "Noto Sans Tifinagh",
  "Noto Sans Tirhuta", "Noto Sans Ugaritic", "Noto Sans Vai", "Noto Sans Wancho",
  "Noto Sans Warang Citi", "Noto Sans Yi", "Noto Sans Zanabazar Square",
  "Noto Serif", "Noto Serif Armenian", "Noto Serif Bengali", "Noto Serif Devanagari",
  "Noto Serif Dogra", "Noto Serif Ethiopic", "Noto Serif Georgian", "Noto Serif Gujarati",
  "Noto Serif Gurmukhi", "Noto Serif Hebrew", "Noto Serif Kannada", "Noto Serif Khmer",
  "Noto Serif Khojki", "Noto Serif Lao", "Noto Serif Malayalam", "Noto Serif Myanmar",
  "Noto Serif Oriya", "Noto Serif Sinhala", "Noto Serif Tamil", "Noto Serif Tangut",
  "Noto Serif Telugu", "Noto Serif Thai", "Noto Serif Tibetan", "Noto Serif Yezidi",
  "Noto Traditional Nushu", "Nova Cut", "Nova Flat", "Nova Mono", "Nova Oval",
  "Nova Round", "Nova Script", "Nova Slim", "Nova Square", "Numans", "Nunito",
  "Nunito Sans", "Nuosu", "Odor Mean Chey", "Offside", "Oi", "Old Standard TT",
  "Oldenburg", "Ole", "Oleo Script", "Oleo Script Swash Caps", "Onest", "Open Sans",
  "Oranienbaum", "Orbitron", "Oregano", "Oregano", "Orienta", "Original Surfer",
  "Oswald", "Outfit", "Over the Rainbow", "Overlock", "Overlock SC", "Overpass",
  "Overpass Mono", "Ovo", "Oxanium", "Oxygen", "Oxygen Mono", "PT Mono", "PT Sans",
  "PT Sans Caption", "PT Sans Narrow", "PT Serif", "PT Serif Caption", "Pacifico",
  "Padauk", "Padyakke Expanded One", "Palanquin", "Palanquin Dark", "Pangolin",
  "Paprika", "Parisienne", "Passero One", "Passion One", "Passions Conflict",
  "Pathway Extreme", "Pathway Gothic One", "Patrick Hand", "Patrick Hand SC",
  "Pattaya", "Patua One", "Pavanam", "Paytone One", "Peddana", "Peralta", "Petit Formal Script",
  "Petrona", "Philosopher", "Phudu", "Piazzolla", "Pie", "Piedra", "Pinyon Script",
  "Pirata One", "Plaster", "Play", "Playball", "Playfair", "Playfair Display",
  "Playfair Display SC", "Plus Jakarta Sans", "Podkova", "Poiret One", "Poller One",
  "Poly", "Pompiere", "Pontano Sans", "Poor Story", "Poppins", "Port Lligat Caption",
  "Port Lligat Slab", "Potta One", "Prata", "Preahvihear", "Press Start 2P",
  "Pridi", "Princess Sofia", "Prociono", "Prompt", "Prosto One", "Proza Libre",
  "Public Sans", "Puppert", "Puritan", "Purple Purse", "Qahiri", "Quanto", "Quattrocento",
  "Quattrocento Sans", "Questrial", "Quicksand", "Quintessential", "Qwigley",
  "Qwitcher Grypen", "Racing Sans One", "Radley", "Rajdhani", "Rakkas", "Raleway",
  "Raleway Dots", "Ramabhadra", "Ramaraja", "Rambla", "Rammetto One", "Rampart One",
  "Ranchers", "Rancho", "Ranga", "Rasa", "Rationale", "Ravi Prakash", "Readex Pro",
  "Recursive", "Red Hat Display", "Red Hat Mono", "Red Hat Text", "Redrose",
  "Reenie Beanie", "Reggae One", "Revalia", "Rhodium Libre", "Ribeye", "Ribeye Marrow",
  "Righteous", "Risque", "Road Rage", "Roboto", "Roboto Condensed", "Roboto Flex",
  "Roboto Mono", "Roboto Serif", "Roboto Slab", "Rochester", "Rock Salt",
  "Rokkitt", "Romanesco", "Ropa Sans", "Rosario", "Rosarivo", "Rouge Script",
  "Rowdies", "Rozha One", "Rubik", "Rubik 80s Fade", "Rubik Beastly", "Rubik Bubbles",
  "Rubik Burned", "Rubik Distressed", "Rubik Glitch", "Rubik Iso", "Rubik Lines",
  "Rubik Marker Hatch", "Rubik Maze", "Rubik Microbe", "Rubik Moonrocks",
  "Rubik Puddles", "Rubik Wet Paint", "Ruda", "Rufina", "Ruge Boogie", "Ruluko",
  "Rum Raisin", "Ruslan Display", "Russo One", "Ruthie", "Rye", "STIX Two Text",
  "Sacramento", "Sahitya", "Sail", "Saira", "Saira Condensed", "Saira Extra Condensed",
  "Saira Semi Condensed", "Saira Stencil One", "Salsa", "Sanchez", "Sancreek",
  "Sansita", "Sansita Swashed", "Sarabun", "Sarala", "Sarina", "Sarpanch",
  "Sassy Frass", "Satisfy", "Saurashtra", "Sawarabi Gothic", "Sawarabi Mincho",
  "Scada", "Scheherazade New", "Schoolbell", "Scope One", "Seaweed Script",
  "Secular One", "Sedgwick Ave", "Sedgwick Ave Display", "Sen", "Sevillana",
  "Seymour One", "Shadows Into Light", "Shadows Into Light Two", "Shalimar",
  "Shanti", "Share", "Share Tech", "Share Tech Mono", "Shippori Mincho",
  "Shippori Mincho B1", "Shrikhand", "Siemreap", "Sigmar", "Sigmar One", "Signika",
  "Signika Negative", "Silkscreen", "Simonetta", "Single Day", "Sintony",
  "Sirin Stencil", "Six Caps", "Skranji", "Slabo 13px", "Slabo 27px", "Slackey",
  "Smokum", "Smooch", "Smooch Sans", "Smythe", "Sniglet", "Snippet", "Snowburst One",
  "Sofadi One", "Sofia", "Sofia Sans", "Sofia Sans Condensed", "Sofia Sans Extra Condensed",
  "Sofia Sans Semi Condensed", "Solitreo", "Solway", "Song Myung", "Sono", "Sora",
  "Sorts Mill Goudy", "Source Code Pro", "Source Sans 3", "Source Sans Pro",
  "Source Serif 4", "Source Serif Pro", "Space Grotesk", "Space Mono", "Special Elite",
  "Spectral", "Spectral SC", "Spicy Rice", "Spinnaker", "Spirax", "Spline Sans",
  "Spline Sans Mono", "Squada One", "Sree Krushnadevaraya", "Sriracha", "Stalemate",
  "Stalinist One", "Stardos Stencil", "Stataco", "Step", "Stint Ultra Condensed",
  "Stint Ultra Expanded", "Stoke", "Strait", "Style Script", "Stylish", "Sue Ellen Francisco",
  "Suez One", "Sulphur Point", "Sumana", "Sunshiney", "Supermercado One",
  "Sura", "Suranna", "Suravaram", "Suwannaphum", "Swanky and Moo Moo", "Syncopate",
  "Syne", "Syne Mono", "Tactile", "Tagu", "Tai Heritage Pro", "Tajawal", "Tangerine",
  "Tant", "Taprom", "Tauri", "Taviraj", "Teko", "Telex", "Tenali Ramakrishna",
  "Tenor Sans", "Text Me One", "Texturina", "Thabit", "Thasadith", "The Girl Next Door",
  "Tienne", "Tila", "Tillana", "Tilt Neon", "Tilt Prism", "Tilt Warp", "Timmana",
  "Tinos", "Tiro Bangla", "Tiro Devanagari Hindi", "Tiro Devanagari Marathi",
  "Tiro Devanagari Sanskrit", "Tiro Gurmukhi", "Tiro Kannada", "Tiro Tamil",
  "Tiro Telugu", "Titan One", "Titillium Web", "Tomorrow", "Tourney", "Townsend",
  "Trade Winds", "Train One", "Trirong", "Trispace", "Trocchi", "Trochut",
  "Truculenta", "Trykker", "Tulpen One", "Turret Road", "Ubuntu", "Ubuntu Condensed",
  "Ubuntu Mono", "Uchen", "Ultra", "Unbounded", "Uncial Antiqua", "Underdog",
  "Unica One", "UnifrakturCook", "UnifrakturMaguntia", "Unkempt", "Unlock",
  "Unna", "Updock", "Urbanist", "VT323", "Vampiro One", "Varela", "Varela Round",
  "Vasa", "Vast Shadow", "Vesper Libre", "Viaoda Libre", "Vibur", "Vidaloka",
  "Viga", "Villa", "Vina Sans", "Vincas", "Ving", "Vollkorn", "Vollkorn SC",
  "Volkhov", "Voltaire", "Vremne", "Waiting for the Sunrise", "Wallpoet",
  "Walter Turncoat", "Warnes", "Water Brush", "Waterfall", "Wave", "Wellfleet",
  "Wendy One", "Whisper", "WindSong", "Wire One", "Work Sans", "Xanh Mono",
  "Yaldevi", "Yanone Kaffeesatz", "Yantramanav", "Yatra One", "Yellowtail",
  "Yeon Sung", "Yeseva One", "Yesteryear", "Yive", "Yizhi", "Yomogi", "Young Serif",
  "Yusei Magic", "Zantant", "Zcool KuaiLe", "Zcool QingKe HuangYou", "Zcool XiaoWei",
  "Zen Dots", "Zen Kaku Gothic Antique", "Zen Kaku Gothic New", "Zen Maru Gothic",
  "Zen Old Mincho", "Zen Tokyo Zoo", "Zeyada", "Zhi Mang Xing", "Zilla Slab",
  "Zilla Slab Highlight"
];

const SUBHEADING_GEOMETRIC = [
  "DM Sans", "Outfit", "Plus Jakarta Sans", "Manrope", "Nunito", "Poppins",
  "Montserrat", "Sora", "Mulish", "Public Sans", "Be Vietnam Pro", "Geist",
  "Albert Sans", "Assistant", "Heebo", "IBM Plex Sans", "Jost", "Lexend",
  "Onest", "Prompt", "Quicksand", "Red Hat Display", "Schibsted Grotesk", "Work Sans",
  "Ubuntu", "Dosis", "Exo", "Exo 2", "Sen", "Spartan", "Questrial", "Marmelad",
  "Jura", "Khand", "Rajdhani", "Teko", "Yantramanav", "Saira", "Syncopate",
  "Nobile", "Pontano Sans", "Varela Round",
  "Almarai", "Amaranth", "Amiko", "Anuphan", "Arimo", "Assistant", "Asul",
  "Atma", "Average Sans", "B612", "Bai Jamjuree", "Baloo 2", "Baloo Paaji 2",
  "Baloo Tamma 2", "Baloo Tammudu 2", "Baloo Thambi 2", "Balsamiq Sans", "Barlow",
  "Barlow Semi Condensed", "Be Vietnam Pro", "Blinker", "Cabin", "Cairo",
  "Catamaran", "Chakra Petch", "Chantilly", "Chivo", "Commissioner", "Cuprum",
  "DM Sans", "Darker Grotesque", "Didact Gothic", "Do Hyeon", "Dosis", "Duru Sans",
  "Economica", "Encode Sans", "Encode Sans Condensed", "Encode Sans Expanded",
  "Encode Sans Semi Condensed", "Encode Sans Semi Expanded", "Epilogue", "Exo",
  "Exo 2", "Fahkwang", "Farro", "Figtree", "Fira Sans", "Fira Sans Condensed",
  "Fira Sans Extra Condensed", "Gantari", "Georama", "Glory", "Golos Text",
  "Heebo", "Hind", "Hind Guntur", "Hind Madurai", "Hind Siliguri", "Hind Vadodara",
  "Homenaje", "Hubballi", "IBM Plex Sans", "IBM Plex Sans Arabic",
  "IBM Plex Sans Condensed", "IBM Plex Sans Devanagari", "IBM Plex Sans Hebrew",
  "IBM Plex Sans JP", "IBM Plex Sans KR", "IBM Plex Sans Thai",
  "IBM Plex Sans Thai Looped", "Instrument Sans", "Inter", "Inter Tight", "Jaldi",
  "Jost", "Jua", "Julius Sans One", "Jura", "Kanit", "Kantumruy Pro", "Khula",
  "KoHo", "Kodchasan", "Koh Santepheap", "Kumbh Sans", "Laila", "Lalezar", "Lato",
  "League Spartan", "Lekton", "Lexend", "Lexend Deca", "Lexend Exa", "Lexend Giga",
  "Lexend Peta", "Lexend Tera", "Lexend Zetta", "Libre Franklin", "Livvic", "M PLUS 1",
  "M PLUS 1p", "M PLUS 2", "Mada", "Magra", "Manjari", "Manrope", "Marmelad",
  "Martel Sans", "Maven Pro", "Meera Inimai", "Merriweather Sans", "Metrophobic",
  "Michroma", "Mina", "Molengo", "Montserrat", "Montserrat Alternates", "Mukta",
  "Mukta Mahee", "Mukta Malar", "Mukta Vaani", "Mulish", "Murecho", "MuseoModerno",
  "Natural", "Naza", "Nehuen", "News Cycle", "Niramit", "Nobile", "Nokora", "Noto Kufi Arabic",
  "Noto Sans", "Noto Sans Adlam", "Noto Sans Adlam Unjoined", "Noto Sans Arabic",
  "Noto Sans Armenian", "Noto Sans Balinese", "Noto Sans Bamum", "Noto Sans Bengali",
  "Noto Sans Canadian Aboriginal", "Noto Sans Cherokee", "Noto Sans Devanagari",
  "Noto Sans Ethiopic", "Noto Sans Georgian", "Noto Sans Gujarati", "Noto Sans Gurmukhi",
  "Noto Sans Hebrew", "Noto Sans JP", "Noto Sans Javanese", "Noto Sans KR",
  "Noto Sans Kannada", "Noto Sans Khmer", "Noto Sans Lao", "Noto Sans Lao Looped",
  "Noto Sans Malayalam", "Noto Sans Meetei Mayek", "Noto Sans Myanmar",
  "Noto Sans NKo", "Noto Sans Oriya", "Noto Sans SC", "Noto Sans Sinhala",
  "Noto Sans TC", "Noto Sans Tamil", "Noto Sans Telugu", "Noto Sans Thaana",
  "Noto Sans Thai", "Noto Sans Thai Looped", "Numans", "Nunito", "Nunito Sans",
  "Offside", "Onest", "Open Sans", "Orbitron", "Orienta", "Outfit", "Overpass",
  "Oxanium", "Oxygen", "PT Sans", "PT Sans Caption", "PT Sans Narrow", "Palanquin",
  "Pathway Extreme", "Pathway Gothic One", "Pavanam", "Philosopher", "Play",
  "Plus Jakarta Sans", "Poiret One", "Pontano Sans", "Poppins", "Pridi", "Prompt",
  "Puritan", "Questrial", "Quicksand", "Rajdhani", "Raleway", "Ramabhadra",
  "Readex Pro", "Red Hat Display", "Red Hat Text", "Redrose", "Roboto",
  "Roboto Condensed", "Roboto Flex", "Ropa Sans", "Rosario", "Rubik", "Ruda",
  "Saira", "Saira Condensed", "Saira Extra Condensed", "Saira Semi Condensed",
  "Sarabun", "Sarala", "Sarpanch", "Scada", "Secular One", "Sen", "Share",
  "Share Tech", "Signika", "Signika Negative", "Sintony", "Sofia Sans",
  "Sofia Sans Condensed", "Sofia Sans Extra Condensed", "Sofia Sans Semi Condensed",
  "Sora", "Source Sans 3", "Source Sans Pro", "Space Grotesk", "Spinnaker",
  "Spline Sans", "Sulphur Point", "Syncopate", "Syne", "Tajawal", "Tauri", "Teko",
  "Telex", "Tenali Ramakrishna", "Text Me One", "Thasadith", "Titillium Web",
  "Tomorrow", "Trispace", "Ubuntu", "Ubuntu Condensed", "Unbounded", "Urbanist",
  "Varela", "Varela Round", "Viga", "Vina Sans", "Voltaire", "Work Sans", "Yantramanav"
];

const SUBHEADING_HUMANIST = [
  "Inter", "Source Sans 3", "Work Sans", "Open Sans", "Lato", "Karla", "Roboto",
  "Libre Franklin", "Figtree", "Hanken Grotesk", "Spline Sans", "Cabin", "Asap",
  "Alegreya Sans", "Bitter", "Cairo", "Catamaran", "Fira Sans", "Hind",
  "Josefin Sans", "M PLUS 1", "Overpass", "Oxygen", "PT Sans", "Sarabun", "Titillium Web",
  "Noto Sans", "Varela", "Signika", "Cantarell", "Carrois Gothic", "Didact Gothic", 
  "Mada", "Ropa Sans",
  "Alegreya Sans", "Alegreya Sans SC", "Andika", "Arimo", "Assistant", "Asul",
  "Average Sans", "B612", "Be Vietnam Pro", "Bitter", "Cabin", "Cairo", "Cantarell",
  "Carrois Gothic", "Carrois Gothic SC", "Catamaran", "Commissioner", "Cuprum",
  "Didact Gothic", "Dosis", "Exo", "Exo 2", "Fira Sans", "Fira Sans Condensed",
  "Fira Sans Extra Condensed", "Gantari", "Gelasio", "Hind", "Hind Guntur",
  "Hind Madurai", "Hind Siliguri", "Hind Vadodara", "IBM Plex Sans",
  "IBM Plex Sans Arabic", "IBM Plex Sans Condensed", "IBM Plex Sans Devanagari",
  "IBM Plex Sans Hebrew", "IBM Plex Sans JP", "IBM Plex Sans KR",
  "IBM Plex Sans Thai", "IBM Plex Sans Thai Looped", "Instrument Sans", "Inter",
  "Inter Tight", "Jaldi", "Jost", "Karla", "Laila", "Lato", "League Spartan",
  "Libre Franklin", "Livvic", "M PLUS 1", "M PLUS 1p", "M PLUS 2", "Mada", "Magra",
  "Manjari", "Manrope", "Martel Sans", "Maven Pro", "Meera Inimai", "Merriweather Sans",
  "Metrophobic", "Mina", "Molengo", "Montserrat", "Montserrat Alternates", "Mukta",
  "Mukta Mahee", "Mukta Malar", "Mukta Vaani", "Mulish", "Murecho", "MuseoModerno",
  "Niramit", "Nobile", "Nokora", "Noto Kufi Arabic", "Noto Sans", "Noto Sans Adlam",
  "Noto Sans Adlam Unjoined", "Noto Sans Arabic", "Noto Sans Armenian",
  "Noto Sans Balinese", "Noto Sans Bamum", "Noto Sans Bengali", "Noto Sans Canadian Aboriginal",
  "Noto Sans Cherokee", "Noto Sans Devanagari", "Noto Sans Ethiopic", "Noto Sans Georgian",
  "Noto Sans Gujarati", "Noto Sans Gurmukhi", "Noto Sans Hebrew", "Noto Sans JP",
  "Noto Sans Javanese", "Noto Sans KR", "Noto Sans Kannada", "Noto Sans Khmer",
  "Noto Sans Lao", "Noto Sans Lao Looped", "Noto Sans Malayalam", "Noto Sans Meetei Mayek",
  "Noto Sans Myanmar", "Noto Sans NKo", "Noto Sans Oriya", "Noto Sans SC",
  "Noto Sans Sinhala", "Noto Sans TC", "Noto Sans Tamil", "Noto Sans Telugu",
  "Noto Sans Thaana", "Noto Sans Thai", "Noto Sans Thai Looped", "Numans",
  "Nunito", "Nunito Sans", "Open Sans", "Overpass", "Oxygen", "PT Sans",
  "PT Sans Caption", "PT Sans Narrow", "Palanquin", "Pathway Extreme",
  "Pathway Gothic One", "Pavanam", "Philosopher", "Plus Jakarta Sans",
  "Pontano Sans", "Poppins", "Prompt", "Puritan", "Quicksand", "Raleway",
  "Readex Pro", "Red Hat Display", "Red Hat Text", "Redrose", "Roboto",
  "Roboto Condensed", "Roboto Flex", "Ropa Sans", "Rosario", "Rubik", "Ruda",
  "Saira", "Saira Condensed", "Saira Extra Condensed", "Saira Semi Condensed",
  "Sarabun", "Sarala", "Sarpanch", "Scada", "Signika", "Signika Negative",
  "Sintony", "Sofia Sans", "Sofia Sans Condensed", "Sofia Sans Extra Condensed",
  "Sofia Sans Semi Condensed", "Sora", "Source Sans 3", "Source Sans Pro",
  "Spline Sans", "Sulphur Point", "Tajawal", "Thasadith", "Titillium Web",
  "Trispace", "Ubuntu", "Ubuntu Condensed", "Varela", "Varela Round", "Work Sans",
  "Yantramanav"
];

const BODY_READABLE = [
  "Inter", "Source Sans 3", "Work Sans", "Open Sans", "Lato", "Karla", "Roboto",
  "Libre Franklin", "Archivo Narrow", "Montserrat", "Lexend", "Mulish", "Figtree",
  "Atkinson Hyperlegible", "Geist", "Spline Sans", "Asap", "Crimson Text",
  "David Libre", "Fauna One", "Gudea", "Istok Web", "Jura", "Maven Pro",
  "Nunito Sans", "Palanquin", "Proza Libre", "Radio Canada", "Ruda", "Vesper Libre",
  "Source Sans Pro", "Oswald", "Raleway", "PT Sans", "Merriweather", "Nunito", 
  "Rubik", "Lora", "Fira Sans", "Quicksand", "Barlow", "Inconsolata", "Titillium Web", 
  "Heebo", "Mukta", "PT Serif", "DM Sans", "Hind", "Bitter", "Oxygen", "Cabin", 
  "Dosis", "Anton", "Cairo", "Exo 2", "Fjalla One", "Libre Baskerville", "Signika", 
  "Varela Round", "Arimo", "Abel", "Assistant", "Tinos",
  "Adamina", "Alike", "Almendra", "Andada Pro", "Anonymous Pro", "Arbutus Slab",
  "Arima", "Arimo", "Arsenal", "Asap", "Assistant", "Average", "Baskervville",
  "Belgrano", "Bellefair", "Benne", "Bentham", "Besley", "Bitter", "Bona Nova",
  "Brawler", "Bree Serif", "Brygada 1918", "Buenard", "Caladea", "Cambay",
  "Cambo", "Cantata One", "Cardo", "Carme", "Castoro", "Caudex", "Chathura",
  "Commissioner", "Content", "Copse", "Cormorant", "Cormorant Garamond",
  "Cormorant Infant", "Cormorant SC", "Coustard", "Crimson Pro", "Crimson Text",
  "Cuprum", "Cutive", "DM Sans", "DM Serif Text", "Darker Grotesque", "David Libre",
  "Didact Gothic", "Domine", "Donegal One", "EB Garamond", "Eczar", "Enriqueta",
  "Esteban", "Fauna One", "Faustina", "Fenix", "Figtree", "Fira Sans", "Fjord One",
  "Frank Ruhl Libre", "GFS Didot", "Gelasio", "Gentium Book Plus", "Gentium Plus",
  "Gidugu", "Gilda Display", "Glegoo", "Goudy Bookletter 1911", "Gowun Batang",
  "Gudea", "Habibi", "Hahmlet", "Halant", "Hanken Grotesk", "Harmattan",
  "Headland One", "Heebo", "Hepta Slab", "Hina Mincho", "Hind", "Ibarra Real Nova",
  "Imprima", "Inika", "Inknut Antiqua", "Inria Sans", "Inria Serif", "Instrument Sans",
  "Instrument Serif", "Inter", "Inter Tight", "Istok Web", "Jacques Francois",
  "Jaldi", "Jost", "Judson", "Junge", "Jura", "Kadwa", "Kaisei Decol", "Kaisei Opti",
  "Kaisei Tokumin", "Kameron", "Kanit", "Karla", "Karma", "Khula", "Kiwi Maru",
  "Klee One", "KoHo", "Kosugi", "Kosugi Maru", "Kotta One", "Kreon", "Kufam",
  "Kulim Park", "Kurale", "Laila", "Lante", "Lato", "Ledger", "Lexend", "Lexend Deca",
  "Lexend Exa", "Lexend Giga", "Lexend Peta", "Lexend Tera", "Lexend Zetta",
  "Libre Baskerville", "Libre Bodoni", "Libre Caslon Text", "Libre Franklin",
  "Literata", "Livvic", "Lora", "Lundy", "Lusitana", "Lustria", "M PLUS 1",
  "M PLUS 1p", "M PLUS 2", "Mada", "Maitree", "Manjari", "Manrope", "Markazi Text",
  "Martel", "Martel Sans", "Mate", "Maven Pro", "Meera Inimai", "Merienda",
  "Merriweather", "Merriweather Sans", "Metrophobic", "Milonga", "Mina", "Mingzat",
  "Molengo", "Mondina", "Montaga", "Montserrat", "Mukta", "Mukta Mahee",
  "Mukta Malar", "Mukta Vaani", "Mulish", "Murecho", "NTR", "Nanum Gothic",
  "Nanum Myeongjo", "Niramit", "Nobile", "Nokora", "Noticia Text", "Noto Kufi Arabic",
  "Noto Naskh Arabic", "Noto Rashi Hebrew", "Noto Sans", "Noto Sans Arabic",
  "Noto Sans Armenian", "Noto Sans Bengali", "Noto Sans Canadian Aboriginal",
  "Noto Sans Cherokee", "Noto Sans Devanagari", "Noto Sans Ethiopic", "Noto Sans Georgian",
  "Noto Sans Gujarati", "Noto Sans Gurmukhi", "Noto Sans Hebrew", "Noto Sans JP",
  "Noto Sans KR", "Noto Sans Kannada", "Noto Sans Khmer", "Noto Sans Lao",
  "Noto Sans Malayalam", "Noto Sans Myanmar", "Noto Sans Oriya", "Noto Sans SC",
  "Noto Sans Sinhala", "Noto Sans TC", "Noto Sans Tamil", "Noto Sans Telugu",
  "Noto Sans Thaana", "Noto Sans Thai", "Noto Serif", "Noto Serif Armenian",
  "Noto Serif Bengali", "Noto Serif Devanagari", "Noto Serif Ethiopic",
  "Noto Serif Georgian", "Noto Serif Gujarati", "Noto Serif Gurmukhi",
  "Noto Serif Hebrew", "Noto Serif Kannada", "Noto Serif Khmer", "Noto Serif Lao",
  "Noto Serif Malayalam", "Noto Serif Myanmar", "Noto Serif Oriya",
  "Noto Serif Sinhala", "Noto Serif Tamil", "Noto Serif Telugu", "Noto Serif Thai",
  "Noto Serif Tibetan", "Numans", "Nunito", "Nunito Sans", "Onest", "Open Sans",
  "Oranienbaum", "Orienta", "Overpass", "Ovo", "Oxygen", "PT Sans", "PT Sans Caption",
  "PT Sans Narrow", "PT Serif", "PT Serif Caption", "Padauk", "Palanquin",
  "Pathway Extreme", "Pathway Gothic One", "Petrona", "Philosopher", "Piazzolla",
  "Playfair", "Plus Jakarta Sans", "Podkova", "Poly", "Pontano Sans", "Poppins",
  "Prata", "Pridi", "Prompt", "Prociono", "Prosto One", "Proza Libre", "Public Sans",
  "Puritan", "Quattrocento", "Quattrocento Sans", "Questrial", "Quicksand",
  "Radley", "Rajdhani", "Raleway", "Rasa", "Rationale", "Readex Pro", "Recursive",
  "Red Hat Display", "Red Hat Text", "Rhodium Libre", "Roboto", "Roboto Condensed",
  "Roboto Flex", "Roboto Serif", "Roboto Slab", "Ropa Sans", "Rosario", "Rosarivo",
  "Rubik", "Ruda", "Rufina", "Ruluko", "STIX Two Text", "Sahitya", "Saira",
  "Saira Semi Condensed", "Sanchez", "Sansita", "Sarabun", "Sarala", "Scada",
  "Scheherazade New", "Scope One", "Secular One", "Sen", "Shanti", "Share",
  "Shippori Mincho", "Shippori Mincho B1", "Signika", "Signika Negative", "Sintony",
  "Slabo 13px", "Slabo 27px", "Solway", "Song Myung", "Source Sans 3",
  "Source Sans Pro", "Source Serif 4", "Source Serif Pro", "Spectral", "Spline Sans",
  "Sree Krushnadevaraya", "Suez One", "Sulphur Point", "Sumana", "Sura", "Suranna",
  "Suravaram", "Suwannaphum", "Tajawal", "Taviraj", "Telex", "Tenor Sans",
  "Text Me One", "Texturina", "Thasadith", "Tienne", "Tillana", "Timmana", "Tinos",
  "Tiro Bangla", "Tiro Devanagari Hindi", "Tiro Gurmukhi", "Tiro Kannada",
  "Tiro Tamil", "Tiro Telugu", "Titillium Web", "Trocchi", "Trykker", "Ubuntu",
  "Ubuntu Condensed", "Uchen", "Unna", "Urbanist", "Varela", "Varela Round",
  "Vesper Libre", "Viaoda Libre", "Vidaloka", "Vina Sans", "Vollkorn", "Volkhov",
  "Work Sans", "Yantramanav", "Yatra One", "Yeon Sung", "Yeseva One", "Young Serif",
  "Zilla Slab"
];

const BODY_MONO = [
  "IBM Plex Mono", "JetBrains Mono", "Roboto Mono", "Fira Code", "Space Mono",
  "Geist Mono", "Anonymous Pro", "Courier Prime", "Cutive Mono", "Inconsolata",
  "Noto Sans Mono", "Overpass Mono", "Source Code Pro", "VT323", "Share Tech Mono", 
  "PT Mono", "Ubuntu Mono", "Spline Sans Mono", "Syne Mono", "Victor Mono", 
  "Red Hat Mono", "Major Mono Display", "Martian Mono", "B612 Mono", "Chivo Mono", 
  "Cousine", "DM Mono", "Fantasque Sans Mono", "Fira Mono", "Nova Mono", 
  "Oxygen Mono", "Sono",
  "Azeret Mono", "B612 Mono", "Chivo Mono", "Cutive Mono", "DM Mono", "Fira Code",
  "Fira Mono", "Fragment Mono", "Geist Mono", "IBM Plex Mono", "Inconsolata",
  "JetBrains Mono", "Lekton", "M PLUS 1 Code", "Major Mono Display", "Martian Mono",
  "Nanum Gothic Coding", "Noto Sans Mono", "Nova Mono", "Overpass Mono", "Oxygen Mono",
  "PT Mono", "Red Hat Mono", "Roboto Mono", "Share Tech Mono", "Sono",
  "Source Code Pro", "Space Mono", "Spline Sans Mono", "Syne Mono", "Ubuntu Mono",
  "VT323", "Victor Mono", "Xanh Mono"
];

const CAPTION_POOL = [
  "IBM Plex Mono", "JetBrains Mono", "Geist Mono", "Space Mono", "Roboto Mono",
  "Karla", "Inter", "Atkinson Hyperlegible", "Lexend", "Geist", "Public Sans",
  "Hanken Grotesk", "Figtree", "Barlow", "Barlow Condensed", "Readex Pro",
  "Red Hat Text", "Urbanist", "PT Mono", "Ubuntu Mono", "Fira Mono", "Cousine", 
  "DM Mono", "Inconsolata", "Fira Sans Condensed", "Roboto Condensed", "Cabin Condensed", 
  "Oswald",
  "Aldrich", "Barlow Condensed", "Cabin Condensed", "Fira Sans Condensed", "Heebo",
  "IBM Plex Sans Condensed", "Inter", "Karla", "Lexend Deca", "Nanum Gothic",
  "Noto Sans", "Oswald", "PT Sans Caption", "PT Sans Narrow", "PT Serif Caption",
  "Pathway Gothic One", "Public Sans", "Roboto Condensed", "Saira Condensed",
  "Saira Extra Condensed", "Saira Semi Condensed", "Sofia Sans Condensed",
  "Sofia Sans Extra Condensed", "Sofia Sans Semi Condensed", "Ubuntu Condensed"
];

const FONT_VIBES: Record<string, string> = {
  "Playfair Display": "Editorial",
  "DM Serif Display": "Geometric",
  "Fraunces": "Warm Modern",
  "Cormorant Garamond": "Luxury",
  "Libre Caslon Display": "Classical",
  "EB Garamond": "Timeless",
  "Bodoni Moda": "Fashion",
  "Crimson Pro": "Long-form",
  "Lora": "Approachable",
  "Tenor Sans": "Luxury",
  "Merriweather": "Trustworthy",
  "Spectral": "Editorial",
  "PT Serif": "Classic",
  "Vollkorn": "Sturdy",
  "Source Serif 4": "Reliable",
  "Newsreader": "Newsroom",
  "Marcellus": "Refined",
  "Libre Bodoni": "Couture",
  "Old Standard TT": "Classical",
  "Libre Baskerville": "Bookish",
  "Yeseva One": "Statement",
  "Syne": "Experimental",
  "Bricolage Grotesque": "Expressive",
  "Space Grotesk": "Modern",
  "Archivo": "Newsroom",
  "Rubik": "Soft",
  "Raleway": "Elegant",
  "Montserrat": "Geometric",
  "Karla": "Functional",
  "Bebas Neue": "Cinematic",
  "Anton": "Headline",
  "Antonio": "Compact",
  "Familjen Grotesk": "Studio",
  "Chivo": "Editorial Sans",
  "Hanken Grotesk": "Crisp",
  "Sora": "Tech",
  "Unbounded": "Futuristic",
  "Big Shoulders Display": "Bold",
  "Geist": "Vercel",
  "Figtree": "Approachable",
  "Lexend": "Readable",
  "Atkinson Hyperlegible": "Accessible",
  "Arapey": "Vintage",
  "Arvo": "Slab",
  "BioRhyme": "Eclectic",
  "Cabinet Grotesque": "High-fashion",
  "Calistoga": "Retro",
  "Cinzel": "Cinematic",
  "Clash Display": "Brutalist",
  "Darker Grotesque": "Modern",
  "Fugaz One": "Sporty",
  "Goldman": "Cyber",
  "Inknut Antiqua": "Literary",
  "Josefin Serif": "Elegant",
  "Kumbh Sans": "Modern",
  "Orbitron": "Futuristic",
  "Oswald": "Compact",
  "Outfit": "Tech",
  "Passion One": "Impactful",
  "Righteous": "Modernist",
  "Russo One": "Techno",
  "Titan One": "Heavy",
  "Tomorrow": "Sci-Fi",
  "Urbanist": "Geometric",
  "Zilla Slab": "Technical",
  "Roboto Slab": "Engineering",
  "Alegreya": "Literary",
  "Neuton": "Compact Serif",
  "Aleo": "Friendly Slab",
  "Bree Serif": "Approachable",
  "Rokkitt": "Robust",
  "Josefin Slab": "Geometric Serif",
  "Knewave": "Brush",
  "Krona One": "Wide Sans",
  "Bungee": "Urban",
  "Carter One": "Retro",
  "Chewy": "Playful",
  "Shrikhand": "Bold",
  "Fredoka": "Rounded",
  "Alfa Slab One": "Heavy",
  "Concert One": "Vintage",
  "Londrina Solid": "Urban",
  "Luckiest Guy": "Comic",
  "Monoton": "Neon",
  "Ubuntu": "Linux",
  "Dosis": "Soft",
  "Exo 2": "Tech",
  "Sen": "Clean",
  "Rajdhani": "Tech",
  "Syncopate": "Wide",
  "Varela Round": "Clean",
  "Fira Sans": "Mozilla",
  "Noto Sans": "Universal",
  "PT Sans": "Functional",
  "Signika": "Signage",
  "Titillium Web": "Tech",
  "Source Sans Pro": "Adobe",
  "Arimo": "Standard",
  "VT323": "Retro Terminal",
  "Share Tech Mono": "Digital",
  "Victor Mono": "Coding",
  "Fira Mono": "Developer",
  "Inconsolata": "Terminal",
  "Roboto Condensed": "Dense",
  "Aboreto": "Artistic",
  "Adamina": "Classical",
  "Afacad Flux": "Modern",
  "Alike": "Academic",
  "Almendra": "Medieval",
  "Andada Pro": "Sturdy",
  "Antic Slab": "Modern Slab",
  "Averia Serif Libre": "Organic",
  "Balthazar": "Classical",
  "Belgrano": "Classic",
  "Besley": "Editorial",
  "Blaka": "Decorative",
  "Brawler": "Sturdy",
  "Caladea": "Reliable",
  "Cantata One": "Elegant",
  "Capriola": "Friendly",
  "Chathura": "Condensed",
  "Coda": "Bold",
  "Codystar": "Neon",
  "Cormorant Infant": "Graceful",
  "Coustard": "Robust",
  "Della Respira": "Classical",
  "Donegal One": "Newspaper",
  "Eagle Lake": "Calligraphic",
  "Economica": "Compact",
  "Electrolize": "Tech",
  "Euphoria Script": "Playful",
  "Fanwood Text": "Classical",
  "Federo": "Vintage",
  "Fenix": "Classic",
  "Forum": "Antique",
  "Gabriela": "Soft",
  "Gafata": "Clean",
  "Galindo": "Cartoon",
  "Gentium Book Plus": "Literary",
  "Germania One": "Heritage",
  "Gloria Hallelujah": "Handwritten",
  "Goblin One": "Impactful",
  "Grand Hotel": "Script",
  "Great Vibes": "Elegant Script",
  "Griffy": "Playful",
  "Habibi": "Professional",
  "Happy Monkey": "Cheerful",
  "Harmattan": "Arabic Style",
  "Henny Penny": "Whimsical",
  "Ibarra Real Nova": "Spanish Style",
  "Indie Flower": "Handmade",
  "Inika": "Approachable",
  "Italiana": "Italian Fashion",
  "Jaldi": "Humanist",
  "Jim Nightshade": "Dark",
  "Jockey One": "Athletic",
  "Jolly Lodger": "Retro Comic",
  "Judson": "Bookish",
  "Kaisei Decol": "Japanese Aesthetic",
  "Kaushan Script": "Brush",
  "Khand": "Compact",
  "Kirang Haerang": "Bold Script",
  "Klee One": "Hand-inked",
  "Kulim Park": "Minimal",
  "Kumar One": "Decorative",
  "Kurale": "Sanskrit Style",
  "La Belle Aurore": "Cursive",
  "Lalezar": "Impactful",
  "Lante": "Graceful",
  "Lateef": "Flowing",
  "Leckerli One": "Script",
  "Ledger": "Professional",
  "Lekton": "Technical",
  "Lemon": "Bold",
  "Literata": "Editorial",
  "Liu Jian Mao Cao": "Chinese Brush",
  "Livvic": "Friendly",
  "Lobster": "Classic Script",
  "Love Ya Like A Sister": "Girly",
  "Lugrasimo": "Artistic",
  "Luminari": "Ancient",
  "Lusitana": "Classical",
  "Luxurious Roman": "Luxury",
  "Ma Shan Zheng": "Ink Script",
  "Macondo": "Art Deco",
  "Mada": "Modern Arab",
  "Maiden Orange": "Funky",
  "Major Mono Display": "Futuristic",
  "Manrope": "Tech",
  "Marck Script": "Casual",
  "Marhey": "Modern Arab",
  "Marko One": "Childrens",
  "Maven Pro": "Modern",
  "MedievalSharp": "Gothic",
  "Megrim": "Experimental",
  "Meow Script": "Playful",
  "Merienda": "Curvy",
  "Metal Mania": "Heavy Metal",
  "Michroma": "Tech",
  "Milonga": "Tango",
  "Miniver": "Soft",
  "Miss Fajardose": "Elegant Script",
  "Modak": "Balloon",
  "Monofett": "Stencil",
  "Mountains of Christmas": "Holiday",
  "Mr Dafoe": "Retro Script",
  "Mrs Sheppards": "Vintage Hand",
  "Nabla": "3D",
  "Nanum Brush Script": "Ink Script",
  "Nanum Myeongjo": "Academic",
  "Nerko One": "Casual",
  "Niconne": "Script",
  "Nixie One": "Neon",
  "Nosifer": "Gothic",
  "Notable": "Signage",
  "Oleo Script": "Retro",
  "Onest": "Modern",
  "Pacifico": "Surf",
  "Palanquin": "Humanist",
  "Parisienne": "French",
  "Passions Conflict": "Calligraphy",
  "Pattaya": "Display",
  "Patua One": "Robust",
  "Peralta": "Funky",
  "Petrona": "Graceful",
  "Phudu": "Modern",
  "Pirata One": "Pirate",
  "Plaster": "Brutalist",
  "Playball": "Sports",
  "Playfair": "Luxury",
  "Podkova": "Slab",
  "Poiret One": "Art Deco",
  "Pompiere": "Tall",
  "Poor Story": "Casual",
  "Potta One": "Blocky",
  "Prata": "Elegant",
  "Press Start 2P": "8-bit",
  "Pridi": "Modern Thai",
  "Princess Sofia": "Fancy",
  "Prosto One": "Russian",
  "Proza Libre": "Humanist",
  "Purple Purse": "Playful",
  "Qwitcher Grypen": "Handwritten",
  "Racing Sans One": "Sporty",
  "Rakkas": "Arab Style",
  "Rammetto One": "Bold",
  "Rampart One": "Decorative",
  "Rancho": "Western",
  "Ranga": "Indian Style",
  "Rasa": "Elegant",
  "Rationale": "Digital",
  "Readex Pro": "Clean",
  "Recursive": "Flexible",
  "Red Hat Display": "Tech",
  "Redrose": "Artistic",
  "Reenie Beanie": "Handwritten",
  "Reggae One": "Street",
  "Road Rage": "Aggressive",
  "Rochester": "Vintage Luxury",
  "Rock Salt": "Grungy",
  "Rouge Script": "Elegant",
  "Rowdies": "Bold Urban",
  "Rozha One": "Heavy",
  "Ruthie": "Cursive",
  "Rye": "Wild West",
  "Sacramento": "Feminine",
  "Sail": "Retro Luxury",
  "Sanchez": "Classic Slab",
  "Sancreek": "Western",
  "Sansita": "Bouncy",
  "Sarina": "Brush",
  "Sarpanch": "Heavy",
  "Satisfy": "Script",
  "Saurashtra": "Traditional",
  "Scada": "Modern",
  "Schoolbell": "Handwritten",
  "Seaweed Script": "Grungy",
  "Secular One": "Hebrew Style",
  "Sedgwick Ave": "Graffiti",
  "Sevillana": "Artistic",
  "Seymour One": "Heavy",
  "Shadows Into Light": "Casual",
  "Shalimar": "Calligraphy",
  "Share Tech": "Digital",
  "Sigmar": "Cartoon",
  "Silkscreen": "Pixel",
  "Single Day": "Casual",
  "Six Caps": "Condensed",
  "Skranji": "Tribal",
  "Slabo 27px": "Academic",
  "Slackey": "Funky",
  "Smokum": "Western",
  "Smooch": "Calligraphy",
  "Smythe": "Gothic",
  "Sofia": "Girly",
  "Solitreo": "Artistic",
  "Sono": "Technical",
  "Special Elite": "Typewriter",
  "Spicy Rice": "Exotic",
  "Squada One": "Athletic",
  "Stalemate": "Ink Script",
  "Stalinist One": "Industrial",
  "Stardos Stencil": "Military",
  "Style Script": "Modern Script",
  "Suez One": "Robust",
  "Sunshiney": "Cheerful",
  "Supermercado One": "Vintage",
  "Tactile": "Physical",
  "Tagu": "Asian Style",
  "Tangerine": "Elegant",
  "Taprom": "Ancient",
  "Tauri": "Functional",
  "Teko": "High-tech",
  "Telex": "Modern",
  "Thabit": "Monospace",
  "Tilt Neon": "Neon",
  "Tilt Warp": "Flexible",
  "Tourney": "Athletic",
  "Trade Winds": "Nautical",
  "Train One": "Speed",
  "Trirong": "Editorial",
  "Trochut": "Art Deco",
  "Tulpen One": "Elegant Tall",
  "Ultra": "Heavy",
  "Uncial Antiqua": "Celtic",
  "Underdog": "Punk",
  "UnifrakturCook": "Fraktur",
  "Unkempt": "Casual",
  "Updock": "Elegant Hand",
  "Vampiro One": "Neon",
  "Vast Shadow": "Decorative",
  "Vibur": "Script",
  "Vidaloka": "Fashion",
  "Villa": "Tech",
  "Vina Sans": "Modern",
  "Wallpoet": "Techno",
  "Walter Turncoat": "Handwritten",
  "Warnes": "Speed",
  "Water Brush": "Soft Script",
  "Wellfleet": "Sturdy",
  "Wendy One": "Playful",
  "WindSong": "Soft Hand",
  "Xanh Mono": "Gothic",
  "Yellowtail": "Classic Script",
  "Yesteryear": "Vintage Script",
  "Yomogi": "Casual Hand",
  "Young Serif": "Vintage Luxury",
  "Zen Dots": "Sci-Fi",
  "Zen Tokyo Zoo": "Experimental",
  "Zeyada": "Handwritten",
  "Zhi Mang Xing": "Chinese Brush"
};

// Curated starting pairings — heading/subheading/body trios. Captions get auto-picked when added.
const buildSlots = (heading: string, subheading: string, body: string, caption: string = "JetBrains Mono"): FontSlot[] => [
  { role: "heading", family: heading },
  { role: "subheading", family: subheading },
  { role: "body", family: body },
  { role: "caption", family: caption },
];

export const FONT_PAIRINGS: FontPairing[] = [
  { id: "fonty-default",      vibe: "Next-gen pairing", slots: buildSlots("Space Grotesk",        "Montserrat",        "Karla") },
  { id: "editorial-classic",  vibe: "Editorial",        slots: buildSlots("Playfair Display",     "Source Sans 3",     "Lato") },
  { id: "modern-saas",        vibe: "Modern SaaS",      slots: buildSlots("Syne",                  "Inter",             "Open Sans") },
  { id: "dm-system",          vibe: "Geometric",        slots: buildSlots("DM Serif Display",      "DM Sans",           "Source Sans 3") },
  { id: "fraunces-inter",     vibe: "Warm Modern",      slots: buildSlots("Fraunces",              "Inter",             "Karla") },
  { id: "bricolage",          vibe: "Expressive",       slots: buildSlots("Bricolage Grotesque",   "DM Sans",           "Inter") },
  { id: "techy-mono",         vibe: "Tech / Crypto",    slots: buildSlots("Space Grotesk",         "Outfit",            "IBM Plex Mono") },
  { id: "luxury-cormorant",   vibe: "Luxury",           slots: buildSlots("Cormorant Garamond",    "Montserrat",        "Lato") },
  { id: "manrope-jakarta",    vibe: "Friendly Tech",    slots: buildSlots("Manrope",               "Plus Jakarta Sans", "Inter") },
  { id: "syne-worksans",      vibe: "Bold Studio",      slots: buildSlots("Syne",                  "Work Sans",         "Karla") },
  { id: "rubik-nunito",       vibe: "Playful",          slots: buildSlots("Rubik",                 "Nunito",            "Karla") },
  { id: "tenor-karla",        vibe: "Boutique",         slots: buildSlots("Tenor Sans",            "Karla",             "Libre Franklin") },
  { id: "bodoni-montserrat",  vibe: "Fashion",          slots: buildSlots("Bodoni Moda",           "Montserrat",        "Lato") },
  { id: "vercel-stack",       vibe: "Vercel",           slots: buildSlots("Geist",                 "Geist",             "Geist Mono") },
  { id: "newsreader-figtree", vibe: "Newsroom",         slots: buildSlots("Newsreader",            "Figtree",           "Figtree") },
  { id: "spectral-hanken",    vibe: "Editorial",        slots: buildSlots("Spectral",              "Hanken Grotesk",    "Lexend") },
  { id: "bebas-inter",        vibe: "Cinematic",        slots: buildSlots("Bebas Neue",            "Inter",             "Inter") },
  { id: "anton-mulish",       vibe: "Headline",         slots: buildSlots("Anton",                 "Mulish",            "Mulish") },
  { id: "marcellus-public",   vibe: "Refined",          slots: buildSlots("Marcellus",             "Public Sans",       "Public Sans") },
  { id: "unbounded-figtree",  vibe: "Future",           slots: buildSlots("Unbounded",             "Figtree",           "Inter") },
  { id: "yeseva-mulish",      vibe: "Statement",        slots: buildSlots("Yeseva One",            "Mulish",            "Lato") },
  { id: "vollkorn-asap",      vibe: "Sturdy",           slots: buildSlots("Vollkorn",              "Asap",              "Asap") },
  { id: "libre-baskerville",  vibe: "Bookish",          slots: buildSlots("Libre Baskerville",     "Lato",              "Lato") },
  { id: "chivo-roboto",       vibe: "Editorial Sans",   slots: buildSlots("Chivo",                 "Roboto",            "Roboto Mono") },
  { id: "sora-jetbrains",     vibe: "Friendly Tech",    slots: buildSlots("Sora",                  "Sora",              "JetBrains Mono") },
  { id: "antonio-figtree",    vibe: "Compact",          slots: buildSlots("Antonio",               "Figtree",           "Figtree") },
  { id: "ptserif-lato",       vibe: "Classic",          slots: buildSlots("PT Serif",              "Lato",              "Lato") },
  { id: "playfair-spline",    vibe: "Boutique",         slots: buildSlots("Playfair Display",      "Spline Sans",       "Spline Sans") },
];


const WEIGHTS = "wght@400;500;600;700";
const encodeFamily = (family: string) =>
  `family=${family.replace(/\s+/g, "+")}:${WEIGHTS}`;

export function buildUrlForFamilies(families: string[]): string {
  if (families.length === 0) return "";
  const uniqueFamilies = Array.from(new Set(families));
  const params = uniqueFamilies.map(encodeFamily).join("&");
  return `https://fonts.googleapis.com/css2?${params}&display=swap`;
}

export const cssFamily = (family: string) => `"${family}", system-ui, sans-serif`;

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function pickExcluding<T>(arr: T[], ...exclude: T[]): T {
  const pool = arr.filter((x) => !exclude.includes(x));
  return pool.length > 0 ? pick(pool) : pick(arr);
}

export function pickFamilyForRole(role: FontRole, exclude: string[] = []): string {
  let pool: string[];
  switch (role) {
    case "heading":
      pool = [...HEADING_SERIFS, ...HEADING_DISPLAY_SANS];
      break;
    case "subheading":
      pool = [...SUBHEADING_GEOMETRIC, ...SUBHEADING_HUMANIST];
      break;
    case "body":
      pool = BODY_READABLE;
      break;
    case "caption":
      pool = CAPTION_POOL;
      break;
  }
  return pickExcluding(pool, ...exclude);
}

// Roll new families for the slots that are NOT locked. Preserves slot order and roles.
export function rollPairing(current: FontPairing, locks: Record<FontRole, boolean>): FontPairing {
  const newSlots: FontSlot[] = [];
  const used: string[] = [];
  for (const slot of current.slots) {
    if (locks[slot.role]) {
      newSlots.push(slot);
      used.push(slot.family);
      continue;
    }
    const family = pickFamilyForRole(slot.role, used);
    newSlots.push({ role: slot.role, family });
    used.push(family);
  }
  const headingFamily = newSlots.find((s) => s.role === "heading")?.family;
  const vibe = (headingFamily && FONT_VIBES[headingFamily]) || "Classic";
  const randomId = Math.random().toString(36).slice(2, 9);
  return { id: `roll-${Date.now()}-${randomId}`, vibe, slots: newSlots };
}

// Used to build a fresh pairing of the requested length (for migrations / new sessions)
export function pickRandomPairing(count: number = 4): FontPairing {
  const roleOrder: FontRole[] = ["heading", "subheading", "body", "caption"];
  const slots: FontSlot[] = [];
  const used: string[] = [];
  for (let i = 0; i < Math.min(count, MAX_SLOTS); i++) {
    const role = roleOrder[i];
    const family = pickFamilyForRole(role, used);
    slots.push({ role, family });
    used.push(family);
  }
  const headingFamily = slots[0]?.family;
  const vibe = (headingFamily && FONT_VIBES[headingFamily]) || "Classic";
  return { id: `roll-${Date.now()}`, vibe, slots };
}
